name: test

on: ['push', 'pull_request']

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14.17'

      - name: install dependencies
        run: yarn install

      - name: build
        run: yarn build

      - name: test:eslint
        run: yarn lint